pretrained_model_path: "./ckpt/stable-diffusion-v1-5"
logdir: ./result/instance_level/2_cats/3cls_samoyed_vs_tiger_under_sunrise

dataset_config:
    path: "data/2_cats/2_cats"  
    prompt: "Cats are playing with toys"
    start_sample_frame: 0
    n_sample_frame: 24
    sampling_rate: 1
    layout_mask_dir: "data/2_cats/layout_masks"
    layout_mask_order: ['left','right','bg'] 
    negative_promot: "ugly, blurry, low res, unrealistic, unaesthetic"

control_config:
    control_type: "depth"
    pretrained_controlnet_path: "./ckpt/sd-controlnet-depth"
    controlnet_conditioning_scale: 0.7

editing_config:
    use_invertion_latents: true
    inject_step: 0
    old_qk: 1
    flatten_res: [1]
    guidance_scale: 7.5
    use_pnp: false
    use_freeu: false
    editing_prompts: [   
            ['A small Samoyed and a tiger are under sunrise','A small Samoyed','a tiger','under sunrise'],
    ]
    clip_length: "${..dataset_config.n_sample_frame}"
    sample_seeds: [0]
    num_inference_steps: 50
    blending_percentage: 0
    modulated_percentage: 0.3
    

test_pipeline_config:
    target: video_diffusion.pipelines.ddim_spatial_temporal.DDIMSpatioTemporalStableDiffusionPipeline
    num_inference_steps: "${..validation_sample_logger.num_inference_steps}"



seed: 42