pretrained_model_path: "./ckpt/stable-diffusion-v1-5"
logdir: ./result/soely_edit/run_two_man/only_right_to_spiderman

dataset_config:
    path: "data/run_two_man/run_two_man_fr2"
    prompt: Man in red hoddie and man in gray shirt are jogging in forest
    n_sample_frame: 16
    start_sample_frame: 0
    sampling_rate: 2
    layout_mask_dir: "./data/run_two_man/layout_masks_fr2"
    layout_mask_order: ['right_v2','trunk']
    negative_promot: "ugly, blurry, low res, unrealistic, unaesthetic"

control_config:
    control_type: "dwpose"
    pretrained_controlnet_path:  "./ckpt/control_v11p_sd15_openpose" 
    controlnet_conditioning_scale: 1.0
    hand: True
    face: False

editing_config:
    use_invertion_latents: true
    inject_step: 0
    old_qk: 1
    flatten_res: [1]
    guidance_scale: 7.5
    use_pnp: true
    use_freeu: false
    editing_prompts: [
           ['red man and Spiderman are jogging under green trees','Spiderman',''],
    ]
        
    clip_length: "${..dataset_config.n_sample_frame}"
    sample_seeds: [0]
    num_inference_steps: 50
    blending_percentage: 0
    

test_pipeline_config:
    target: video_diffusion.pipelines.ddim_spatial_temporal.DDIMSpatioTemporalStableDiffusionPipeline
    num_inference_steps: "${..validation_sample_logger.num_inference_steps}"



seed: 42

