pretrained_model_path: "./ckpt/stable-diffusion-v1-5"
logdir: ./result/part_level/part_level_modification/man_text_message/black_suit

dataset_config:
    path: "data/man_text_message/man_text_message"
    prompt: A man in casual shirt is texting message
    start_sample_frame: 0
    n_sample_frame: 16
    sampling_rate: 1
    layout_mask_dir: "data/man_text_message/layout_masks"
    layout_mask_order: ['suit','suit_bg']
    negative_promot: "jittery, ugly, blurry, low res, unrealistic, unaesthetic"
    
control_config:
   control_type: "dwpose"
   pretrained_controlnet_path:  "./ckpt/control_v11p_sd15_openpose"
   controlnet_conditioning_scale: 1.0
   hand: true
   face: false
 
editing_config:
    use_invertion_latents: true
    inject_step: 10
    old_qk: 1
    flatten_res: [1,2,4]
    guidance_scale: 7.5
    use_pnp: true
    use_freeu: false
    editing_prompts: [
        ['A man in black suit','black suit'],
    ]
    clip_length: "${..dataset_config.n_sample_frame}"
    sample_seeds: [0]
    num_inference_steps: 50
    blending_percentage: 0

test_pipeline_config:
    target: video_diffusion.pipelines.ddim_spatial_temporal.DDIMSpatioTemporalStableDiffusionPipeline
    num_inference_steps: "${..validation_sample_logger.num_inference_steps}"



seed: 42

