pretrained_model_path: "./ckpt/stable-diffusion-v1-5"
logdir: ./result/instance_level/badminton/left_wonder_woman_right_spiderman

dataset_config:
    path: "data/badminton/badminton"
    prompt: a man and a woman are playing badminton
    start_sample_frame: 7
    n_sample_frame: 24
    sampling_rate: 1
    layout_mask_dir: "./data/badminton/layout_masks"
    layout_mask_order: ['man','woman','bg']
    negative_promot: "jittery, ugly, blurry, low res, unrealistic, unaesthetic"

control_config:
   control_type: "dwpose"
   pretrained_controlnet_path: "./ckpt/control_v11p_sd15_openpose"
   controlnet_conditioning_scale: 1.0
   hand: True
   face: True


editing_config:
    use_inversion_attention: true
    use_invertion_latents: true
    inject_step: 12
    old_qk: 1
    flatten_res: [1,2]
    guidance_scale: 7.5
    use_pnp: true
    use_freeu: false
    editing_prompts: [
        ['A Spider Man and a Wonder Woman are before charcoal grey wall','A Spider Man','Wonder Woman','charcoal grey wall'],

    ]
    clip_length: "${..dataset_config.n_sample_frame}"
    sample_seeds: [0]
    num_inference_steps: 50
    blending_percentage: 0
    

test_pipeline_config:
    target: video_diffusion.pipelines.ddim_spatial_temporal.DDIMSpatioTemporalStableDiffusionPipeline
    num_inference_steps: "${..validation_sample_logger.num_inference_steps}"



seed: 42

