pretrained_model_path: "./ckpt/stable-diffusion-v1-5"
logdir: ./result/class_level/tennis/man_to_ironman

dataset_config:
    path: "data/tennis/tennis"
    prompt: a man
    n_sample_frame: 24
    sampling_rate: 2
    layout_mask_dir: "./data/tennis/layout_masks"
    layout_mask_order: ["man"]
    negative_promot: "jittery, ugly, blurry, low res, unrealistic, unaesthetic"

# use_invertion_latents: True
control_config:
    control_type: "openpose"
    pretrained_controlnet_path: ./ckpt/sd-controlnet-openpose
    #"/home/xianyang/Data/code/FateZero/ckpt/control_v11p_sd15_openpose"
    controlnet_conditioning_scale: 1.0
    hand: false
    face: false

editing_config:
    use_invertion_latents: true
    inject_step: 0
    old_qk: 1
    flatten_res: [1]
    guidance_scale: 7.5
    use_pnp: false
    use_freeu: false
    editing_prompts: [     
            ['An Iron Man'],
    ]
    clip_length: "${..dataset_config.n_sample_frame}"
    sample_seeds: [0]
    num_inference_steps: 50
    blending_percentage: 0.25

    
model_config:
    # lora: 160
    # temporal_downsample_time: 4
    # SparseCausalAttention_index: ['first'] 
    # least_sc_channel: 640
    # least_sc_channel: 100000

test_pipeline_config:
    target: video_diffusion.pipelines.ddim_spatial_temporal.DDIMSpatioTemporalStableDiffusionPipeline
    num_inference_steps: "${..validation_sample_logger.num_inference_steps}"



seed: 42