pretrained_model_path: "ckpt/stable-diffusion-v1-5"
logdir: ./result/part_level/run_two_man/left2spider_right2polar-sunglasses

dataset_config:
    path: "data/run_two_man/run_two_man_fr2"
    prompt: ''
    n_sample_frame: 16
    start_sample_frame: 0
    sampling_rate: 2
    layout_mask_dir: "./data/run_two_man/layout_masks_fr2"
    layout_mask_order: ['left_man','right_man_wo_eyes','eyes_right_man','ground','full_trees']
    negative_promot: "ugly, blurry, low res, unrealistic, unaesthetic"

control_config:
    control_type: "dwpose"
    pretrained_controlnet_path: "./ckpt/control_v11p_sd15_openpose" 
    controlnet_conditioning_scale: 1.0
    hand: True
    face: False

editing_config:
    use_invertion_latents: true
    inject_step: 0
    old_qk: 1
    flatten_res: [1]
    guidance_scale: 7.5
    use_pnp: false
    use_freeu: false
    editing_prompts: [
        ['Spiderman and Polar Bear in sunglasses on grass meadow before cherry trees','Spiderman','Polar Bear','sunglasses','grass meadow','cherry trees'],
    ]
        
    clip_length: "${..dataset_config.n_sample_frame}"
    sample_seeds: [0]
    num_inference_steps: 50
    blending_percentage: 0
    #cluster_inversion_feature: True
    # vis_cross_attn: false

test_pipeline_config:
    target: video_diffusion.pipelines.ddim_spatial_temporal.DDIMSpatioTemporalStableDiffusionPipeline
    num_inference_steps: "${..validation_sample_logger.num_inference_steps}"



seed: 42

